# Generated by Django 4.2.6 on 2025-03-11 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_notification_read_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="cargpt_notifications",
        ),
    ]
